#!/bin/bash
if test -e "/etc/default/grub" ; then
    cp /etc/default/grub default/grub.bak
    echo "Backuped your /etc/default/grub in ./default/grub.bak"
    rm /etc/default/grub;
fi
ln -s "$(pwd)/default/grub" /etc/default/grub
if [[ $? != 0 ]] ; then
    echo "Configuration failed"
    if test -f "default/grub" ; then
        cp default/grub.bak /etc/default/grub;
        if [[ $? == 0 ]] ; then
            echo "Restored /etc/default/grub";
        fi
    fi
    exit;
fi
for file in ./grub.d/* ; do
    ln -s "$(pwd)/$file" "/etc/$file"
    if [[ $? != 0 ]] ; then
        echo "Failed to symlink grub.d/$file";
    fi
done
echo "Finished"

